# Generated by Django 2.2.5 on 2019-09-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.TextField()),
                ('title_year', models.IntegerField()),
                ('movie_imdb_link', models.URLField()),
                ('color', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('aspect_ratio', models.FloatField()),
                ('country', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('gross', models.PositiveIntegerField()),
                ('content_rating', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('num_critic_for_reviews', models.PositiveIntegerField()),
                ('num_voted_users', models.PositiveIntegerField()),
                ('num_user_for_reviews', models.PositiveIntegerField()),
                ('imdb_score', models.FloatField()),
                ('cast_total_facebook_likes', models.PositiveIntegerField()),
                ('movie_facebook_likes', models.IntegerField()),
                ('facenumber_in_poster', models.IntegerField()),
                ('director_name', models.TextField()),
                ('director_facebook_likes', models.PositiveIntegerField()),
                ('actor_1_name', models.TextField()),
                ('actor_1_facebook_likes', models.PositiveIntegerField()),
                ('actor_2_name', models.TextField()),
                ('actor_2_facebook_likes', models.PositiveIntegerField()),
                ('actor_3_name', models.TextField()),
                ('actor_3_facebook_likes', models.PositiveIntegerField()),
                ('genres', models.ManyToManyField(blank=True, null=True, to='movie.Genres')),
                ('plot_keywords', models.ManyToManyField(blank=True, null=True, to='movie.Keywords')),
            ],
        ),
    ]
