# Generated by Django 2.2.5 on 2019-09-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190913_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='role',
            field=models.CharField(choices=[('d', 'Director'), ('a', 'Actor')], default='a', max_length=2),
        ),
    ]
