# Generated by Django 2.2.5 on 2019-09-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_remove_movie_actors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-imdb_score']},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_facebook_likes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_name',
        ),
    ]
