# Generated by Django 2.2.5 on 2019-09-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movieactors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor_1_facebook_likes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actor_1_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actor_2_facebook_likes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actor_2_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actor_3_facebook_likes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actor_3_name',
        ),
    ]
